package com.tkhskt.glsl_tokenizer_kt

val expectedTokens = listOf(
    GlslToken(column = 0, data = "\n", line = 2, position = 0, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "precision", line = 2, position = 1, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 2, position = 10, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "highp", line = 2, position = 11, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 16, data = " ", line = 2, position = 16, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 19, data = "int", line = 2, position = 17, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 19, data = ";", line = 2, position = 20, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 3, position = 21, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "precision", line = 3, position = 22, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 3, position = 31, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "highp", line = 3, position = 32, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 16, data = " ", line = 3, position = 37, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 21, data = "float", line = 3, position = 38, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 21, data = ";", line = 3, position = 43, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 4, position = 44, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "precision", line = 4, position = 45, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 4, position = 54, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "highp", line = 4, position = 55, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 16, data = " ", line = 4, position = 60, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 20, data = "vec2", line = 4, position = 61, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 20, data = ";", line = 4, position = 65, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 5, position = 66, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "precision", line = 5, position = 67, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 5, position = 76, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "highp", line = 5, position = 77, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 16, data = " ", line = 5, position = 82, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 20, data = "vec3", line = 5, position = 83, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 20, data = ";", line = 5, position = 87, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 6, position = 88, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "precision", line = 6, position = 89, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 6, position = 98, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "highp", line = 6, position = 99, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 16, data = " ", line = 6, position = 104, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 20, data = "vec4", line = 6, position = 105, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 20, data = ";", line = 6, position = 109, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 7, position = 110, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 7, data = "#line 0", line = 7, position = 111, type = GlslToken.Type.PREPROCESSOR),
    GlslToken(column = 0, data = "\n\n", line = 9, position = 118, type = GlslToken.Type.WHITESPACE),
    GlslToken(
        column = 7,
        data = "#define X(a) Y \\\n  asdf \\\n  barry",
        line = 11,
        position = 120,
        type = GlslToken.Type.PREPROCESSOR
    ),
    GlslToken(column = 0, data = "\n\n", line = 13, position = 153, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 7, data = "varying", line = 13, position = 155, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 8, data = " ", line = 13, position = 162, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 12, data = "vec2", line = 13, position = 163, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 13, data = " ", line = 13, position = 167, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 22, data = "vTexcoord", line = 13, position = 168, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 22, data = ";", line = 13, position = 177, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 14, position = 178, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 7, data = "varying", line = 14, position = 179, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 8, data = " ", line = 14, position = 186, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 12, data = "vec3", line = 14, position = 187, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 13, data = " ", line = 14, position = 191, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 22, data = "vPosition", line = 14, position = 192, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 22, data = ";", line = 14, position = 201, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 15, position = 202, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 7, data = "uniform", line = 15, position = 203, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 8, data = " ", line = 15, position = 210, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 12, data = "mat4", line = 15, position = 211, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 13, data = " ", line = 15, position = 215, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 17, data = "proj", line = 15, position = 216, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 18, data = ",", line = 15, position = 220, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 19, data = " ", line = 15, position = 221, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 23, data = "view", line = 15, position = 222, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 23, data = ";", line = 15, position = 226, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n\n", line = 17, position = 227, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "attribute", line = 17, position = 229, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 17, position = 238, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 14, data = "vec3", line = 17, position = 239, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 15, data = " ", line = 17, position = 243, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 23, data = "position", line = 17, position = 244, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 23, data = ";", line = 17, position = 252, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 18, position = 253, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "attribute", line = 18, position = 254, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 10, data = " ", line = 18, position = 263, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 14, data = "vec2", line = 18, position = 264, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 15, data = " ", line = 18, position = 268, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 23, data = "texcoord", line = 18, position = 269, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 23, data = ";", line = 18, position = 277, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n\n", line = 20, position = 278, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 4, data = "void", line = 20, position = 280, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 5, data = " ", line = 20, position = 284, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 9, data = "main", line = 20, position = 285, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 9, data = "(", line = 20, position = 289, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 10, data = ")", line = 20, position = 290, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 12, data = "{", line = 20, position = 291, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 4, data = "\n    ", line = 21, position = 292, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 13, data = "vTexcoord", line = 21, position = 297, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 14, data = " ", line = 21, position = 306, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "=", line = 21, position = 307, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 16, data = " ", line = 21, position = 308, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 24, data = "texcoord", line = 21, position = 309, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 24, data = ";", line = 21, position = 317, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 4, data = "\n    ", line = 22, position = 318, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 13, data = "vPosition", line = 22, position = 323, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 14, data = " ", line = 22, position = 332, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "=", line = 22, position = 333, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 16, data = " ", line = 22, position = 334, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 24, data = "position", line = 22, position = 335, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 24, data = ";", line = 22, position = 343, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 4, data = "\n    ", line = 23, position = 344, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 15, data = "gl_Position", line = 23, position = 349, type = GlslToken.Type.BUILT_IN),
    GlslToken(column = 16, data = " ", line = 23, position = 360, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 17, data = "=", line = 23, position = 361, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 18, data = " ", line = 23, position = 362, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 22, data = "proj", line = 23, position = 363, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 23, data = " ", line = 23, position = 367, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 24, data = "*", line = 23, position = 368, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 25, data = " ", line = 23, position = 369, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 29, data = "view", line = 23, position = 370, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 30, data = " ", line = 23, position = 374, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 31, data = "*", line = 23, position = 375, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 32, data = " ", line = 23, position = 376, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 36, data = "vec4", line = 23, position = 377, type = GlslToken.Type.KEYWORD),
    GlslToken(column = 36, data = "(", line = 23, position = 381, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 45, data = "position", line = 23, position = 382, type = GlslToken.Type.IDENTIFIER),
    GlslToken(column = 46, data = ",", line = 23, position = 390, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 47, data = " ", line = 23, position = 391, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 51, data = "1e+0", line = 23, position = 392, type = GlslToken.Type.FLOAT),
    GlslToken(column = 51, data = ")", line = 23, position = 396, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 52, data = ";", line = 23, position = 397, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 0, data = "\n", line = 24, position = 398, type = GlslToken.Type.WHITESPACE),
    GlslToken(column = 1, data = "}", line = 24, position = 399, type = GlslToken.Type.OPERATOR),
    GlslToken(column = 1, data = "(eof)", line = 24, position = 399, type = GlslToken.Type.EOF),
)
