package com.tkhskt.glsl_tokenizer_kt

val expectedTokens = listOf(
    Token(column = 0, data = "\n", line = 2, position = 0, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "precision", line = 2, position = 1, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 2, position = 10, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "highp", line = 2, position = 11, type = Token.Type.KEYWORD),
    Token(column = 16, data = " ", line = 2, position = 16, type = Token.Type.WHITE_SPACE),
    Token(column = 19, data = "int", line = 2, position = 17, type = Token.Type.KEYWORD),
    Token(column = 19, data = ";", line = 2, position = 20, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 3, position = 21, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "precision", line = 3, position = 22, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 3, position = 31, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "highp", line = 3, position = 32, type = Token.Type.KEYWORD),
    Token(column = 16, data = " ", line = 3, position = 37, type = Token.Type.WHITE_SPACE),
    Token(column = 21, data = "float", line = 3, position = 38, type = Token.Type.KEYWORD),
    Token(column = 21, data = ";", line = 3, position = 43, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 4, position = 44, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "precision", line = 4, position = 45, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 4, position = 54, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "highp", line = 4, position = 55, type = Token.Type.KEYWORD),
    Token(column = 16, data = " ", line = 4, position = 60, type = Token.Type.WHITE_SPACE),
    Token(column = 20, data = "vec2", line = 4, position = 61, type = Token.Type.KEYWORD),
    Token(column = 20, data = ";", line = 4, position = 65, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 5, position = 66, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "precision", line = 5, position = 67, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 5, position = 76, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "highp", line = 5, position = 77, type = Token.Type.KEYWORD),
    Token(column = 16, data = " ", line = 5, position = 82, type = Token.Type.WHITE_SPACE),
    Token(column = 20, data = "vec3", line = 5, position = 83, type = Token.Type.KEYWORD),
    Token(column = 20, data = ";", line = 5, position = 87, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 6, position = 88, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "precision", line = 6, position = 89, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 6, position = 98, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "highp", line = 6, position = 99, type = Token.Type.KEYWORD),
    Token(column = 16, data = " ", line = 6, position = 104, type = Token.Type.WHITE_SPACE),
    Token(column = 20, data = "vec4", line = 6, position = 105, type = Token.Type.KEYWORD),
    Token(column = 20, data = ";", line = 6, position = 109, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 7, position = 110, type = Token.Type.WHITE_SPACE),
    Token(column = 7, data = "#line 0", line = 7, position = 111, type = Token.Type.PREPROCESSOR),
    Token(column = 0, data = "\n\n", line = 9, position = 118, type = Token.Type.WHITE_SPACE),
    Token(
        column = 7,
        data = "#define X(a) Y \\\n  asdf \\\n  barry",
        line = 11,
        position = 120,
        type = Token.Type.PREPROCESSOR
    ),
    Token(column = 0, data = "\n\n", line = 13, position = 153, type = Token.Type.WHITE_SPACE),
    Token(column = 7, data = "varying", line = 13, position = 155, type = Token.Type.KEYWORD),
    Token(column = 8, data = " ", line = 13, position = 162, type = Token.Type.WHITE_SPACE),
    Token(column = 12, data = "vec2", line = 13, position = 163, type = Token.Type.KEYWORD),
    Token(column = 13, data = " ", line = 13, position = 167, type = Token.Type.WHITE_SPACE),
    Token(column = 22, data = "vTexcoord", line = 13, position = 168, type = Token.Type.IDENTIFIER),
    Token(column = 22, data = ";", line = 13, position = 177, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 14, position = 178, type = Token.Type.WHITE_SPACE),
    Token(column = 7, data = "varying", line = 14, position = 179, type = Token.Type.KEYWORD),
    Token(column = 8, data = " ", line = 14, position = 186, type = Token.Type.WHITE_SPACE),
    Token(column = 12, data = "vec3", line = 14, position = 187, type = Token.Type.KEYWORD),
    Token(column = 13, data = " ", line = 14, position = 191, type = Token.Type.WHITE_SPACE),
    Token(column = 22, data = "vPosition", line = 14, position = 192, type = Token.Type.IDENTIFIER),
    Token(column = 22, data = ";", line = 14, position = 201, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 15, position = 202, type = Token.Type.WHITE_SPACE),
    Token(column = 7, data = "uniform", line = 15, position = 203, type = Token.Type.KEYWORD),
    Token(column = 8, data = " ", line = 15, position = 210, type = Token.Type.WHITE_SPACE),
    Token(column = 12, data = "mat4", line = 15, position = 211, type = Token.Type.KEYWORD),
    Token(column = 13, data = " ", line = 15, position = 215, type = Token.Type.WHITE_SPACE),
    Token(column = 17, data = "proj", line = 15, position = 216, type = Token.Type.IDENTIFIER),
    Token(column = 18, data = ",", line = 15, position = 220, type = Token.Type.OPERATOR),
    Token(column = 19, data = " ", line = 15, position = 221, type = Token.Type.WHITE_SPACE),
    Token(column = 23, data = "view", line = 15, position = 222, type = Token.Type.IDENTIFIER),
    Token(column = 23, data = ";", line = 15, position = 226, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n\n", line = 17, position = 227, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "attribute", line = 17, position = 229, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 17, position = 238, type = Token.Type.WHITE_SPACE),
    Token(column = 14, data = "vec3", line = 17, position = 239, type = Token.Type.KEYWORD),
    Token(column = 15, data = " ", line = 17, position = 243, type = Token.Type.WHITE_SPACE),
    Token(column = 23, data = "position", line = 17, position = 244, type = Token.Type.IDENTIFIER),
    Token(column = 23, data = ";", line = 17, position = 252, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 18, position = 253, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "attribute", line = 18, position = 254, type = Token.Type.KEYWORD),
    Token(column = 10, data = " ", line = 18, position = 263, type = Token.Type.WHITE_SPACE),
    Token(column = 14, data = "vec2", line = 18, position = 264, type = Token.Type.KEYWORD),
    Token(column = 15, data = " ", line = 18, position = 268, type = Token.Type.WHITE_SPACE),
    Token(column = 23, data = "texcoord", line = 18, position = 269, type = Token.Type.IDENTIFIER),
    Token(column = 23, data = ";", line = 18, position = 277, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n\n", line = 20, position = 278, type = Token.Type.WHITE_SPACE),
    Token(column = 4, data = "void", line = 20, position = 280, type = Token.Type.KEYWORD),
    Token(column = 5, data = " ", line = 20, position = 284, type = Token.Type.WHITE_SPACE),
    Token(column = 9, data = "main", line = 20, position = 285, type = Token.Type.IDENTIFIER),
    Token(column = 9, data = "(", line = 20, position = 289, type = Token.Type.OPERATOR),
    Token(column = 10, data = ")", line = 20, position = 290, type = Token.Type.OPERATOR),
    Token(column = 12, data = "{", line = 20, position = 291, type = Token.Type.OPERATOR),
    Token(column = 4, data = "\n    ", line = 21, position = 292, type = Token.Type.WHITE_SPACE),
    Token(column = 13, data = "vTexcoord", line = 21, position = 297, type = Token.Type.IDENTIFIER),
    Token(column = 14, data = " ", line = 21, position = 306, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "=", line = 21, position = 307, type = Token.Type.OPERATOR),
    Token(column = 16, data = " ", line = 21, position = 308, type = Token.Type.WHITE_SPACE),
    Token(column = 24, data = "texcoord", line = 21, position = 309, type = Token.Type.IDENTIFIER),
    Token(column = 24, data = ";", line = 21, position = 317, type = Token.Type.OPERATOR),
    Token(column = 4, data = "\n    ", line = 22, position = 318, type = Token.Type.WHITE_SPACE),
    Token(column = 13, data = "vPosition", line = 22, position = 323, type = Token.Type.IDENTIFIER),
    Token(column = 14, data = " ", line = 22, position = 332, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "=", line = 22, position = 333, type = Token.Type.OPERATOR),
    Token(column = 16, data = " ", line = 22, position = 334, type = Token.Type.WHITE_SPACE),
    Token(column = 24, data = "position", line = 22, position = 335, type = Token.Type.IDENTIFIER),
    Token(column = 24, data = ";", line = 22, position = 343, type = Token.Type.OPERATOR),
    Token(column = 4, data = "\n    ", line = 23, position = 344, type = Token.Type.WHITE_SPACE),
    Token(column = 15, data = "gl_Position", line = 23, position = 349, type = Token.Type.BUILT_IN),
    Token(column = 16, data = " ", line = 23, position = 360, type = Token.Type.WHITE_SPACE),
    Token(column = 17, data = "=", line = 23, position = 361, type = Token.Type.OPERATOR),
    Token(column = 18, data = " ", line = 23, position = 362, type = Token.Type.WHITE_SPACE),
    Token(column = 22, data = "proj", line = 23, position = 363, type = Token.Type.IDENTIFIER),
    Token(column = 23, data = " ", line = 23, position = 367, type = Token.Type.WHITE_SPACE),
    Token(column = 24, data = "*", line = 23, position = 368, type = Token.Type.OPERATOR),
    Token(column = 25, data = " ", line = 23, position = 369, type = Token.Type.WHITE_SPACE),
    Token(column = 29, data = "view", line = 23, position = 370, type = Token.Type.IDENTIFIER),
    Token(column = 30, data = " ", line = 23, position = 374, type = Token.Type.WHITE_SPACE),
    Token(column = 31, data = "*", line = 23, position = 375, type = Token.Type.OPERATOR),
    Token(column = 32, data = " ", line = 23, position = 376, type = Token.Type.WHITE_SPACE),
    Token(column = 36, data = "vec4", line = 23, position = 377, type = Token.Type.KEYWORD),
    Token(column = 36, data = "(", line = 23, position = 381, type = Token.Type.OPERATOR),
    Token(column = 45, data = "position", line = 23, position = 382, type = Token.Type.IDENTIFIER),
    Token(column = 46, data = ",", line = 23, position = 390, type = Token.Type.OPERATOR),
    Token(column = 47, data = " ", line = 23, position = 391, type = Token.Type.WHITE_SPACE),
    Token(column = 51, data = "1e+0", line = 23, position = 392, type = Token.Type.FLOAT),
    Token(column = 51, data = ")", line = 23, position = 396, type = Token.Type.OPERATOR),
    Token(column = 52, data = ";", line = 23, position = 397, type = Token.Type.OPERATOR),
    Token(column = 0, data = "\n", line = 24, position = 398, type = Token.Type.WHITE_SPACE),
    Token(column = 1, data = "}", line = 24, position = 399, type = Token.Type.OPERATOR),
    Token(column = 1, data = "(eof)", line = 24, position = 399, type = Token.Type.EOF),
)
